version: '3.6'

services:
  client:
    build: 
      context: ./client
      network: host
    container_name: client
    ports:
      - "4173:4173"

  server:
    build:
      context: ./server
      network: host
    container_name: server
    env_file:
      - ./.env
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/app/pb_data
